### PR TITLE
Separating pinned tabs (bookmarks) and unpinned tabs

### PR DESCRIPTION
**Pull request by yinan-c**
Hi! This is not necessarily a bug-fix, but someone might find these changes useful, inspired by #1, I have added location and space names and:

- Separated pinned and unpinned tabs by assigning them to `tabs` and `bm` respectively. 
- Added the space names in the subtitle of the entry - tabs can now be **filtered by the space name.**

However, it still does not fetch favorite tabs, since the favorite tabs are directly under the level of the windows (instead of under spaces as implemented in this workflow)

Now it should look like this:

### CODE REVIEW

**Comment by shp7724** [comment]
Do you by chance have plans to go one step further and support favorites too? 😄 I just installed Arc and was also looking for the solution of #1 .

**Comment by yinan-c** [comment]
@shp7724 I can take a look at that, in principle. I will keep you updated if there is any progress on that.

**Comment by yinan-c** [comment]
@shp7724  Hi! I've updated the workflow to support top tabs (with keyword `tops`), please [have a try](https://github.com/yinan-c/Alfred-Workflow-for-Arc/releases/tag/v1.3) and let me know if it works for you.

**Comment by shp7724** [comment]
Thanks for the quick response! I gave it a try, but have a question:

image

I assigned a hot key for the workflows, expecting that pressing the hot key would let me search from `tops`, `tabs`, and `bm`, but for some reason the search results don't include items from `tops`. Would this be fixable?

**Comment by QIanGua** [comment]
Thanks for your pull 🥳

**Comment by yinan-c** [comment]
@shp7724  Hi, I am able to reproduce the problem - I've tried assigning keyboard hotkey for all 3 script filters. Only `bm` shows results.

However, I've tried with other workflows witch multiple script filters. I think this is probably a behaviour (or a bug?) of Alfred's hotkey function - that it can only trigger one script filter, maybe we can ask [Alfredforum](https://www.alfredforum.com) for help.

Specifically to this workflow, if you want to have a way to show all tabs - regardless of their position - I can possibly modify the workflow a bit to add this functionality.

**Comment by shp7724** [comment]
@yinan-c Yes, I'd greatly appreciate it if you could modify it to add the functionality to search for all tabs. That would be very helpful for my work routine! Thanks.

**Comment by shp7724** [comment]
@yinan-c This is exactly what I wanted. Thank you very much!

**Pull request merged**
